CREATE TABLE posteos(
    id BIGINT NOT NULL AUTO_INCREMENT,
    titulo VARCHAR(300) UNIQUE NOT NULL ,
    mensaje VARCHAR(750) UNIQUE NOT NULL ,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
    estado_posteo VARCHAR(100) DEFAULT 'SIN_LEER' NOT NULL,
    autor VARCHAR(100) NOT NULL ,
    curso VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
)